### ISSUE TITLE
Clarify that phonemes must be supported by the custom model language

### ISSUE THREAD

**Issue by VictorLFandino** [ibm-cloud-docs/text-to-speech#129]
When adding entries to a custom voice model using the phonetic method, it should be more clear than the phonemes provided should be supported by the custom voice model language. 

For instance, when synthesizing a text in Spanish that contains an English word, one can think that a good approach to pronounce that word correctly is to use the pronunciation method with that word in English; then, take the phonetic response and add the word/translation pair to the Spanish custom model. However, you get error saying that ipa characters are not supported, etc.

**Comment by jeffpk62** [comment]
Hi, Victor.  I saw this only recently.  I have added a new section to address this shortcoming.  Thanks for taking the time to post the recommendation!
