### ISSUE TITLE
hello guys. it's looks very complicated

### ISSUE THREAD

**Issue by Caussanel** [ibm-cloud-docs/text-to-speech#131]

**Comment by jeffpk62** [comment]
Hi!  Yeah, it's a programming interface, so there's some basic understanding required.  But if you just want to try it out from the command line, visit this page:

https://cloud.ibm.com/docs/text-to-speech?topic=text-to-speech-gettingStarted

You will need to get credentials and install curl, a command-line utility for making HTTP requests.  But it's actually pretty straightforward for basic speech synthesis.  You can also visit the demo page here:

https://text-to-speech-demo.ng.bluemix.net/

Good luck!
