### ISSUE TITLE
Is this thing even working.?

### ISSUE THREAD

**Issue by ray0992** [ibm-cloud-docs/text-to-speech#137]
I signed up for paid plan. I can't figure how this thing is suppose to work. keep going around in circles. video tutorial doesn't work.

**Comment by jeffpk62** [comment]
The service provides a programming interface, so you need to write code to use it.  You can test it with the simple command-line curl utility.  Anything more elaborate requires use of a real programming language.  There are SDKs that greatly simplify use of the service; they are documented on this page: https://cloud.ibm.com/apidocs/text-to-speech.

There are three places to start using the service:

- The demo that illustrates capabilities (it is an application that is written to the service's programming interface): https://www.ibm.com/demos/live/tts-demo/self-service/home
- The getting started content: https://cloud.ibm.com/docs/text-to-speech?topic=text-to-speech-gettingStarted
- The getting started video, which is just an overview of that content.  I've tried the video in Firefox, Chrome, and Safari, and it appears to be working fine in each.

I'm not sure where you are having problems.  Do you have have an API key to get started?
