### ISSUE TITLE
Needs curl POST example of specifying a voice

### ISSUE THREAD

**Issue by ModalityZ** [ibm-cloud-docs/text-to-speech#141]
After looking at all the linked guidance about how to specify a voice, my best guess was to specify it in a new header like
``` --header "voice=en-US_OliviaV3Voice"```
but I got Michael's voice anyway.

**Comment by jeffpk62** [comment]
@ModalityZ Sorry, there's an updated version of the doc coming soon that includes an example.  For now, here's the example that shows specification of a voice.  Since it's a query parameter, you pass the `voice` on the URL.

```
curl -X POST -u "apikey:{apikey}"
--header "Content-Type: application/json"
--header "Accept: audio/wav"
--data "{\"text\":\"hello world\"}"
--output hello_world.wav
"{url}/v1/synthesize?voice=en-US_AllisonV3Voice"
```
