### ISSUE TITLE
Minor Typo?

### ISSUE THREAD

**Issue by henryjc** [ibm-cloud-docs/text-to-speech#142]
It seems in the documentation linked below there is a missing left opening angle bracket (>); shown in the picture below.

![Capture](https://user-images.githubusercontent.com/10813505/150069224-382023b1-a843-4396-a657-b73e5d198c64.PNG)

link to page: https://cloud.ibm.com/docs/text-to-speech?topic=text-to-speech-ssml

**Comment by jeffpk62** [comment]
Thank you!!  This issue is fixed in the source files and will be correct at the next build of the documentation.
