### ISSUE TITLE
Getting started page link in UI broken

### ISSUE THREAD

**Issue by mekaufman** [ibm-cloud-docs/text-to-speech#144]
If you provision an instance of text to speech, click on the instance from your resource list, and then go to the Getting started page, the last link on the page to the API docs is broken. You can see the original issue reporting this issue here: https://github.com/ibm-cloud-docs/overview/issues/40

**Comment by jeffpk62** [comment]
@mekaufman Can you see whether this is also broken in services like Discovery and Assistant, please?  A recent change to IBM Cloud docs has caused problems for us with `{DomianName}`.  The links works fine in the actual documentation.  I'm trying to determine whether this is specific to Speech or affects all of our Watson docs.  Thanks.

**Comment by mekaufman** [comment]
@jeffpk62 Switch to using a relative path link and the issue in the reuse will be fixed.

**Comment by jeffpk62** [comment]
@mekaufman There are a couple of possible solutions to try, that being the first.  But I am concerned that many Watson services will have the same issue.  Since support for `{DomainName}` resolution changed recently, we've encountered this issue in other areas as well.

**Comment by jeffpk62** [comment]
This is fixed for both Speech to Text and Text to Speech.
