### ISSUE TITLE
Will the arabic voice ever make a return ?

### ISSUE THREAD

**Issue by gaandurian** [ibm-cloud-docs/text-to-speech#145]
Hey, trying to synthesise some arabic text using the TTS service, I found the **ar-MS_OmarVoice** in the docs , but couldn't use it.
Now after stumbling upon the changelog I found out that it was completely removed.

### My question is. Will it ever make a return to the service?

**Comment by jeffpk62** [comment]
Hello, @gaandurian.  The existing `ar-MS_OmarVoice` is not available to new users, those who created accounts after 31 March 2022.

> New users: Instances of the service created on or after 31 March 2022 cannot use the deprecated voices for speech synthesis. The instances also cannot be used create custom models that are based on the deprecated voices. And they cannot list or query the voices with the GET /v1/voices and GET /v1/voices/{voice} methods. Any API call that includes one of the deprecated voices returns an HTTP error code of 400 or 404, depending on the call.

A new version of the voice is not currently planned for availability.  That could always change at some point in the future, but is not planned at the moment.  I apologize for the slow response; I was out for the holidays.
