### ISSUE TITLE
two or more languages 

### ISSUE THREAD

**Issue by jgajardo** [ibm-cloud-docs/text-to-speech#78]
Please, could you help me for synthesize two or more languages in the same synthesize function call?

response = text_to_speech.synthesize(assistant_text_output, accept='audio/l16;rate=8000',voice="<<<spanish and english>>>").get_result()

**Comment by jeffpk62** [comment]
@jgajardo I do not believe that the service supports synthesis of two different voices with the same call.  You likely need to use different calls for audio in the separate voices.
